version: 0.2

env: 
   
   parameter-store:
                Mongo_Uri: "/sheoran/mongo_url"

phases:
   build:
       commands:
           - sed -i "s/database_uri/"$Mongo_Uri"/" app.js  



artifacts:
        files: 
            - " **/* "
